### ISSUE TITLE
Apk? 

### ISSUE THREAD

**Issue by HyperCriSiS** [FliegendeWurst/TriliumDroid#1]
Hi,
Awesome that you are working on an Android app for Trilium!
Will you release an apk anytime soon or how can I build myself?

Thanks
Hyper

**Comment by FliegendeWurst** [comment]
You can get an APK from the release I just created: https://github.com/FliegendeWurst/TriliumDroid/releases/tag/nightly-2024-05-16

**Comment by HyperCriSiS** [comment]
Awesome, thanks! 🎉
