### ISSUE TITLE
Guesture mode unable to interact 

### ISSUE THREAD

**Issue by MatejPetrik007** [FliegendeWurst/TriliumDroid#21]
<details>

![image](https://github.com/user-attachments/assets/ee6cc32a-c88d-4af2-9fc1-95161465be91)

</details>

on One Plus 5 without guestures 

<details>

![image](https://github.com/user-attachments/assets/fc9758a6-916e-46b3-9f27-83b494921a29)
</details>

all other apps like https://github.com/martinstoeckli/SilentNotes

<details>

![image](https://github.com/user-attachments/assets/1476a132-2924-4a71-b621-2ae5c0daa8e6)
</details>

**Comment by FliegendeWurst** [comment]
What do you mean by "unable to interact"?

**Comment by MatejPetrik007** [comment]
https://github.com/user-attachments/assets/f72ee1e8-94fd-42ee-8095-a4af1d8156f2

**Comment by FliegendeWurst** [comment]
Okay, I see two issues there:

1. Status bar overlapping toolbar
2. Editor toolbar overlapping floating action buttons

Will try to fix for next alpha.
