### ISSUE TITLE
Sync settings not saved when using Bitwarden autofill

### ISSUE THREAD

**Issue by hulmgulm** [FliegendeWurst/TriliumDroid#22]
I've setup my TrilumNext server to be accessible at https://mydomain.com/notes.

Configuring this in TriliumDroid causes a crash once I select Sync in the menu. Unfortunately, I cannot start TriliumDroid after that anymore, as it crashes immediately on each start. I need to delete all the data first.

Looking into the logs of server, I don't see any requests coming from TriliumDroid.

**Comment by FliegendeWurst** [comment]
If you can, please get the logfile from your phone: [stackoverflow.com/questions/2882253/how-do-i-get-the-logfile-from-an-android-device](https://stackoverflow.com/questions/2882253/how-do-i-get-the-logfile-from-an-android-device)

Most sync errors are handled gracefully. I'll have to check what I could have missed.

**Comment by FliegendeWurst** [comment]
Did you specify `https://yourdomain.com/notes/` or `https://yourdomain.com/notes`? At the moment only the latter will work. Next release both will be allowed.

**Comment by hulmgulm** [comment]
At first I tried with a trailing / but the last try was without. I will send you the log by mail.

**Comment by FliegendeWurst** [comment]
Thank you for the logs. The crash is:
```
12-09 18:38:02.846 13026 13701 E AndroidRuntime: java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but no scheme was found for /login
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1261)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1634)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at okhttp3.Request$Builder.url(Request.kt:184)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at eu.fliegendewurst.triliumdroid.ConnectionUtil.connect(ConnectionUtil.kt:79)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at eu.fliegendewurst.triliumdroid.ConnectionUtil.setup(ConnectionUtil.kt:31)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at eu.fliegendewurst.triliumdroid.MainActivity$startSync$1.invokeSuspend(MainActivity.kt:251)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
12-09 18:38:02.846 13026 13701 E AndroidRuntime: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
Apparently the hostname stored in the preferences is empty. I'm not sure how that happened. The code there is rather straightforward: read value from input field, store in preferences.

I added a check that the URL is parsable for the next release, but it won't fix the issue, only prevent the crash.

**Comment by hulmgulm** [comment]
That's strange to see the same error in both logs I sent you. I did entered different URLs in both tries, then entered the password and then pressed the "back" button at the bottom of the screen.

I just tried it again, entering the details as I did before, then going back. But instead of starting sync, I went back to the settings and the URL was empty. 

Now I had an idea! I was not actually entering the password but using Bitwarden to fill it in. Entering the password my self got the URL saved and TriliumDroid does not crash anymore.

**Comment by FliegendeWurst** [comment]
> I was not actually entering the password but using Bitwarden to fill it in. Entering the password my self got the URL saved and TriliumDroid does not crash anymore.

Oh, that is interesting. I wonder what Bitwarden is doing there.. maybe it simulates "submitting" the password and the app doesn't handle that.

**Comment by hulmgulm** [comment]
It looked like the password field got saved, but I cannot validate that as the input field displays just dots.
