### ISSUE TITLE
Screenshots and icon

### ISSUE THREAD

**Issue by IzzySoft** [FliegendeWurst/TriliumDroid#5]
Are there any screenshots and an app icon available? I've just stumbled upon your repo here and thought about adding TrilliumDroid to the [IzzyOnDroid repo](https://apt.izzysoft.de/fdroid) if you don't mind :wink: Thanks in advance!

**Comment by IzzySoft** [comment]
> The icon should be somewhere in the resources.

I've looked there already, only found XML. We unfortunately cannot use that but need a PNG.

> Should I put all that in a fastlane directory?

That would be perfect indeed, thanks! If you need any guidance with that, be welcome to use the [IzzyOnDroid Fastlane Documentation](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) as reference :wink:

**Comment by FliegendeWurst** [comment]
I added the fastlane metadata here: https://github.com/FliegendeWurst/TriliumDroid/tree/master/fastlane/metadata/android/en-US

Let me know if it works for you. Then I can tag and upload the next release.

**Comment by IzzySoft** [comment]
That looks excellent, please go ahead! I meanwhile work on the integration with IzzyOnDroid (will update you here soon today).

**Comment by IzzySoft** [comment]
Quick injection before you make the release, from the scanner report here:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

This can easily be avoided with a minor addition to your `build.gradle`:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains. More details can be found e.g. here: [Ramping up security: additional APK checks are in place with the IzzyOnDroid repo](https://android.izzysoft.de/articles/named/iod-scan-apkchecks#blobs).

Thanks in advance!

**Comment by IzzySoft** [comment]
One more thing:

    buildConfigField "long", "TIMESTAMP", System.currentTimeMillis() + "L"

Please don't do that. This makes [Reproducible Builds](https://reproducible-builds.org/) impossible, as it is non-deterministic (will have different results on each run), see e.g. [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients). Can you remove that with the upcoming release, please?

**Comment by FliegendeWurst** [comment]
Thanks for the heads-up. I fixed the BLOB for this release, the timestamp will be fixed next release :)
(I think the timestamp configuration was in the default app template.)

**Comment by FliegendeWurst** [comment]
> Hope you did not forget to increase `versionCode`; your fastlane seems to say you thought of it. And it would be great if the tag names could somehow reflect the `versionName` (or the `versionCode`), e.g. `v0.59.4` or `v1`.

I did increase the version code and also removed the timestamp :) https://github.com/FliegendeWurst/TriliumDroid/blob/48af2bd614466024475e65c62e91e72513219c3c/app/build.gradle#L14-L15

As for the tag name, "alpha1" corresponds to versionName = "0.90.12-alpha1". The first part of the version is not that relevant to me, it's just the latest version of the desktop app tested for compatibility. I will make the tag name equal to `v$versionName` in the future.

> PackageName changed with the new release I see. This is the final one, right?

Yes. I changed it because I got the domain in the meantime.

**Comment by IzzySoft** [comment]
> I did increase the version code and also removed the dynamic timestamp

:partying_face:

> As for the tag name, "alpha1" corresponds to versionName = "0.90.12-alpha1".

The updater of the IzzyOnDroid repo usually goes by the tag names. It currently would look for any tags greater than "0.90.12-alpha1" then, evaluating them by the standards of [semantic versioning](https://semver.org/) – which cannot work.

So I've now configured your app here so the updater ignores the tag name and just compares the date of the attached APK. That **usually** works, but there are sometimes quirks I could not yet figure how they happen, where at each run it thinks the very same file at Github is newer (by the value Github API reports), leading to the same APK being downloaded over and again, once each day. So I try keeping this kind of configuration to a minimum (that quirk only happens occasionally – but when it happens, the useless download-and-delete-the-file circle goes on until the next release was made).

Well, let's see how it goes. Maybe TrilliumDroid is not affected at all.

> Yes. I changed it because I got the domain in the meantime.

Congrats! :partying_face:
